{
    "Animated": true,
    "Duration": 2,
    "Message": "Entity created",
    "IsIconHidden": true,
    "OnSuccess": "/MDK_ErrorArchive/Actions/CloseModalPage_Complete.action",
    "_Type": "Action.Type.ToastMessage"
}