{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/multiuserapp/Pages/com_sap_edm_sampleservice_v4_SalesOrderHeaders/SalesOrderHeaders_CreateSalesOrderItem.page",
    "_Type": "Action.Type.Navigation"
}