{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "PurchaseOrderHeaders",
        "Service": "/mdkapp/Services/com_sap_edm_sampleservice_v4.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "CurrencyCode": "#Control:CurrencyCode/#Value",
        "GrossAmount": "#Control:GrossAmount/#Value",
        "NetAmount": "#Control:NetAmount/#Value",
        "PurchaseOrderID": "#Control:PurchaseOrderID/#Value",
        "SupplierID": "#Control:SupplierID/#SelectedValue",
        "TaxAmount": "#Control:TaxAmount/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/mdkapp/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/mdkapp/Actions/UpdateEntityFailureMessage.action"
}