{
    "PopoverItems": [{
            "Title": "Add PurchaseOrderItem",
            "OnPress": "/mdkapp/Actions/com_sap_edm_sampleservice_v4/PurchaseOrderHeaders/NavToPurchaseOrderHeaders_CreatePurchaseOrderItem.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/mdkapp/Rules/com_sap_edm_sampleservice_v4/PurchaseOrderHeaders/PurchaseOrderHeaders_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}