{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MultiUserApp/Pages/SampleServiceV4_SalesOrderHeaders/SalesOrderHeaders_CreateSalesOrderItem.page",
    "_Type": "Action.Type.Navigation"
}