{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "CreateSalesOrderHeaderEntityFailureMessage"
	},
	"Message": "Failed to Create Sales Order record - {#ActionResults:SalesOrderHeaders_CreateEntity/error}",
	"Title": "Create Sales Order",
	"OKCaption": "OK"
}