{
	"_Type": "Action.Type.ToastMessage",
	"ActionResult": {
		"_Name": "LogUploadSuccessful"
	},
	"Message": "Log File Uploaded",
	"NumberOfLines": 1,
	"Duration": 3,
	"IsIconHidden": true,
	"Animated": true
}