{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "LogUploadFailure"
	},
	"Message": "Failed to upload client logs - {#ActionResults:LogUpload/error}",
	"Title": "Upload Client Logs",
	"OKCaption": "OK"
}