{
	"_Type": "Action.Type.ODataService.CreateRelatedEntity",
	"ActionResult": {
		"_Name": "SalesOrderHeaders_CreateEntity"
	},
	"OnFailure": {
		"Name": "/DemoSampleApp/Actions/GenericMessageBox.action",
		"Properties": {
			"Message": "Failed to Create Sales Order record - {#ActionResults:SalesOrderHeaders_CreateEntity/error}",
			"Title": "Create Sales Order"
		}
	},
	"OnSuccess": "/DemoSampleApp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/DemoSampleApp/Services/SampleServiceV4.service",
		"EntitySet": "SalesOrderHeaders"
	},
	"ParentLink": {
		"Target": {
			"EntitySet": "Customers",
			"ReadLink": "{@odata.readLink}"
		},
		"Property": "SalesOrders"
	},
	"Properties": {
		"CreatedAt": "#Control:FCCreatedate/#Value",
		"CurrencyCode": "#Control:FCCreateCurrencyCode/#Value",
		"GrossAmount": "#Control:FCCreateGrossAmount/#Value",
		"LifeCycleStatus": "#Control:FCCreateLifeCycleStatus/#Value",
		"LifeCycleStatusName": "#Control:FCCreateLifeCycleStatusName/#Value",
		"NetAmount": "#Control:FCCreateNetAmount/#Value",
		"TaxAmount": "#Control:FCCreateTaxAmount/#Value"
	}
}