{
    "PopoverItems": [{
            "Title": "Add SalesOrderHeader",
            "OnPress": "/multiuserapp/Actions/SampleServiceV4/Customers/NavToCustomers_CreateSalesOrderHeader.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/multiuserapp/Rules/SampleServiceV4/Customers/Customers_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}