{
	"Service": "/MDK_Maps/Services/SampleService.service",
	"_Type": "Action.Type.ODataService.Open",
	"OnSuccess": "/MDK_Maps/Actions/Service/CreateOpenServiceSuccessMessage.action",
	"OnFailure": "/MDK_Maps/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ActionResult": {
		"_Name": "init"
	}
}