{
	"Service": "/mdk_maps/Services/SampleServiceV2.service",
	"_Type": "Action.Type.ODataService.Open",
	"OnSuccess": "/mdk_maps/Actions/Service/CreateOpenServiceSuccessMessage.action",
	"OnFailure": "/mdk_maps/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ActionResult": {
		"_Name": "init"
	}
}