{
    "PopoverItems": [{
            "Title": "Add SalesOrderItem",
            "OnPress": "/MultiUserApp/Actions/SalesOrderHeaders/NavToSalesOrderHeaders_CreateSalesOrderItem.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/MultiUserApp/Rules/SalesOrderHeaders/SalesOrderHeaders_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}