{
    "Service": "/mdk_annotations/Services/SampleServiceV4.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnFailure": "/mdk_annotations/Actions/SampleServiceV4/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}