{
	"Service": "/MDK_Styling/Services/SampleService.service",
	"DefiningRequests": [
	{
		"Name": "Customers",
		"Query": "Customers"
	}
],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/MDK_Styling/Actions/Service/SyncFailureMessage.action"
}