{
    "Service": "/MDK_Styling/Services/SampleServiceV4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/MDK_Styling/Actions/Service/SyncFailureMessage.action",
    "OnSuccess": "/MDK_Styling/Rules/ErrorArchive/ErrorArchive_CheckForSyncError.js"
}