{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/mdkapp/Pages/com_sap_edm_sampleservice_v4_Suppliers/Suppliers_CreateProduct.page",
    "_Type": "Action.Type.Navigation"
}