{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "PurchaseOrderItems",
        "Service": "/MDK_ErrorArchive/Services/SampleServiceV4.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "CurrencyCode": "#Control:CurrencyCode/#Value",
        "GrossAmount": "#Control:GrossAmount/#Value",
        "ItemNumber": "#Control:ItemNumber/#Value",
        "NetAmount": "#Control:NetAmount/#Value",
        "ProductID": "#Control:ProductID/#SelectedValue",
        "PurchaseOrderID": "#Control:PurchaseOrderID/#SelectedValue",
        "Quantity": "#Control:Quantity/#Value",
        "QuantityUnit": "#Control:QuantityUnit/#Value",
        "TaxAmount": "#Control:TaxAmount/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/MDK_ErrorArchive/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/MDK_ErrorArchive/Actions/UpdateEntityFailureMessage.action"
}