{
	"_Type": "Action.Type.OfflineOData.Close",
	"Service": "/MDKApp/Services/Sample.service",
	"Force": true,
	"ActionResult": {
		"_Name": "close"
	},
	"OnSuccess": "/MDKApp/Actions/Service/CloseOfflineSuccessMessage.action",
	"OnFailure": "/MDKApp/Actions/Service/CloseOfflineFailureMessage.action"
}