{
    "Target": {
        "EntitySet": "SalesOrderItems",
        "Service": "/mdkapp/Services/com_sap_edm_sampleservice_v4.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/mdkapp/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/mdkapp/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}