{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MDK_Styling/Pages/SampleServiceV4_Customers/Customers_CreateSalesOrderHeader.page",
    "_Type": "Action.Type.Navigation"
}