{
    "_Type": "Action.Type.ODataService.UploadStream",
    "Target": {
        "Service": "/mdk_errorarchive/Services/com_sap_edm_sampleservice_v4.service",
        "EntitySet": "Products",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "Picture": "#Control:Picture/#Value"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "uploadstream"
    },
    "OnSuccess": "/mdk_errorarchive/Actions/UploadStreamSuccessMessage.action",
    "OnFailure": "/mdk_errorarchive/Actions/UploadStreamFailureMessage.action"
}