{
	"OnFailure": "/DemoSampleApp/Actions/CreateCustomerEntityFailureMessage.action",
	"OnSuccess": "/DemoSampleApp/Actions/CloseModalPage_Complete.action",
	"Properties": {
		"DateOfBirth": "#Control:FCCreateDOB/#Value",
		"EmailAddress": "#Control:FCCreateEmail/#Value",
		"FirstName": "#Control:FCCreateFirstName/#Value",
		"LastName": "#Control:FCCreateLastName/#Value",
		"PhoneNumber": "#Control:FCCreatePhone/#Value"
	},
	"Target": {
		"EntitySet": "Customers",
		"Service": "/DemoSampleApp/Services/Sample.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}