{
	"ActionResult": {
		"_Name": "delete"
	},
	"OnFailure": "/DemoSampleApp/Actions/DeleteCustomerEntityFailureMessage.action",
	"OnSuccess": "/DemoSampleApp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}",
		"Service": "/DemoSampleApp/Services/Sample.service"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity"
}