{
	"_Type": "Action.Type.Logger.Upload",
	"OnFailure": "/DemoSampleApp/Actions/LogUploadFailure.action",
	"OnSuccess": "/DemoSampleApp/Actions/LogUploadSuccessful.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Uploading Logs..."
}