{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/deeplinkintomdkapp/Actions/SampleServiceV4/Service/UploadOffline.action",
    "OnFailure": "/deeplinkintomdkapp/Actions/SampleServiceV4/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}