{
	"CreateLinks": [],
	"OnFailure": "/MDKApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/MDKApp/Actions/CreateEntitySuccessMessage.action",
	"Properties": {
	"CreatedAt": "#Control:CreatedAt/#Value",
	"CurrencyCode": "#Control:CurrencyCode/#Value",
	"CustomerId": "#Control:CustomerId/#Value",
	"GrossAmount": "#Control:GrossAmount/#Value",
	"LifeCycleStatus": "#Control:LifeCycleStatus/#Value",
	"LifeCycleStatusName": "#Control:LifeCycleStatusName/#Value",
	"NetAmount": "#Control:NetAmount/#Value",
	"SalesOrderId": "#Control:SalesOrderId/#Value",
	"TaxAmount": "#Control:TaxAmount/#Value"
},
	"Target": {
		"EntitySet": "SalesOrderHeaders",
		"Service": "/MDKApp/Services/Sample.service"
	},
	"ActionResult": {
		"_Name": "create"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}