{
    "Service": "/MDK_ErrorArchive/Services/SampleServiceV4.service",
    "DefiningRequests": [{
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "Suppliers",
            "Query": "Suppliers"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnSuccess": "/MDK_ErrorArchive/Actions/Service/InitializeOfflineSuccessMessage.action",
    "OnFailure": "/MDK_ErrorArchive/Actions/Service/InitializeOfflineFailureMessage.action"
}