{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/mdkapp/Pages/SampleServiceV4_PurchaseOrderHeaders/PurchaseOrderHeaders_CreatePurchaseOrderItem.page",
    "_Type": "Action.Type.Navigation"
}