{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MDKApp/Pages/SampleServiceV4_PurchaseOrderHeaders/PurchaseOrderHeaders_CreatePurchaseOrderItem.page",
    "_Type": "Action.Type.Navigation"
}