{
    "PopoverItems": [{
            "Title": "Add SalesOrderHeader",
            "OnPress": "/mdk_styling/Actions/com_sap_edm_sampleservice_v4/Customers/NavToCustomers_CreateSalesOrderHeader.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/mdk_styling/Rules/com_sap_edm_sampleservice_v4/Customers/Customers_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}