{
	"_Type": "Action.Type.ODataService.Create",
	"Service": "/MDK_Annotations/Services/SampleServiceV2.service",
	"OnSuccess": "/MDK_Annotations/Actions/Service/OpenService.action",
	"OnFailure": "/MDK_Annotations/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Initializing Application...",
	"ActionResult": {
		"_Name": "init"
	}
}