{
    "CreateLinks": [],
    "OnFailure": "/MDK_ErrorArchive/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/MDK_ErrorArchive/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "City": "#Control:City/#Value",
        "Country": "#Control:Country/#Value",
        "EmailAddress": "#Control:EmailAddress/#Value",
        "HouseNumber": "#Control:HouseNumber/#Value",
        "PhoneNumber": "#Control:PhoneNumber/#Value",
        "PostalCode": "#Control:PostalCode/#Value",
        "Street": "#Control:Street/#Value",
        "SupplierId": "#Control:SupplierId/#Value",
        "SupplierName": "#Control:SupplierName/#Value",
        "UpdatedTimestamp": "#Control:UpdatedTimestamp/#Value"
    },
    "Target": {
        "EntitySet": "Suppliers",
        "Service": "/MDK_ErrorArchive/Services/SampleServiceV2.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}