{
    "_Type": "Action.Type.ODataService.UpdateEntity",
    "Target": {
        "EntitySet": "Suppliers",
        "Service": "/MDK_ErrorArchive/Services/SampleServiceV4.service",
        "ReadLink": "{@odata.readLink}"
    },
    "Properties": {
        "City": "#Control:City/#Value",
        "Country": "#Control:Country/#Value",
        "EmailAddress": "#Control:EmailAddress/#Value",
        "HouseNumber": "#Control:HouseNumber/#Value",
        "PhoneNumber": "#Control:PhoneNumber/#Value",
        "PostalCode": "#Control:PostalCode/#Value",
        "Street": "#Control:Street/#Value",
        "SupplierID": "#Control:SupplierID/#Value",
        "SupplierName": "#Control:SupplierName/#Value"
    },
    "UpdateLinks": [],
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": "/MDK_ErrorArchive/Actions/UpdateEntitySuccessMessage.action",
    "OnFailure": "/MDK_ErrorArchive/Actions/UpdateEntityFailureMessage.action"
}