{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MDK_ErrorArchive/Pages/SampleServiceV4_Products/Products_CreateSalesOrderItem.page",
    "_Type": "Action.Type.Navigation"
}