{
	"CreateLinks": [],
	"OnFailure": "/MDKApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/MDKApp/Actions/CreateEntitySuccessMessage.action",
	"Properties": {
	"City": "#Control:City/#Value",
	"Country": "#Control:Country/#Value",
	"CustomerId": "#Control:CustomerId/#Value",
	"DateOfBirth": "#Control:DateOfBirth/#Value",
	"EmailAddress": "#Control:EmailAddress/#Value",
	"FirstName": "#Control:FirstName/#Value",
	"HouseNumber": "#Control:HouseNumber/#Value",
	"LastName": "#Control:LastName/#Value",
	"PhoneNumber": "#Control:PhoneNumber/#Value",
	"PostalCode": "#Control:PostalCode/#Value",
	"Street": "#Control:Street/#Value",
	"UpdatedTimestamp": "#Control:UpdatedTimestamp/#Value"
},
	"Target": {
		"EntitySet": "Customers",
		"Service": "/MDKApp/Services/Sample.service"
	},
	"ActionResult": {
		"_Name": "create"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}