{
	"Target": {
		"EntitySet": "Customers",
		"Service": "/MDKApp/Services/Sample.service",
		"ReadLink": "{@odata.readLink}"
	},
	"OnSuccess": "/MDKApp/Actions/DeleteEntitySuccessMessage.action",
	"OnFailure": "/MDKApp/Actions/DeleteEntityFailureMessage.action",
	"ActionResult": {
		"_Name": "delete"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity"
}