{
	"_Type": "Action.Type.CheckBarcodeScannerPrerequisite",
	"OnSuccess":"/BarcodeScanning/Rules/BarcodeScanner/CheckBarcodeScannerPrerequisiteResult.js",
	"OnFailure":"/BarcodeScanning/Actions/BarcodeScanner/CheckBarcodeScannerPrerequisiteFailure.action",
	"ActionResult": {
	"_Name": "CheckCamera"
}
}