{
	"_Type": "Action.Type.OpenBarcodeScanner",
	"ActionResult": {
		"_Name": "OpenBarcodeScanner"
	},
	"OnFailure": "/BarcodeScanning/Actions/BarcodeScanner/OpenBarcodeScannerFailure.action",
	"OnSuccess": "/BarcodeScanning/Rules/BarcodeScanner/BarcodeResult_OpenProductDetail.js",
	"_OnSuccess": "/BarcodeScanning/Rules/BarcodeScanner/ShowBarcodeScanningResult.js"
}