{
	"_Type": "Action.Type.OpenBarcodeScanner",
	"ActionResult": {
		"_Name": "BarcodeScanner"
	},
	"OnFailure": {
		"Name": "/BarcodeScanning/Actions/GenericToastMessage.action",
		"Properties": {
			"Message": "Barcode scanning failed",
			"NumberOfLines": 2,
			"Duration": 3
		}
	},
	"OnSuccess": "/BarcodeScanning/Rules/BarcodeScanner/BarcodeScanResult.js"
}