{
    "Service": "/mdk_i18n_l10n/Services/com_sap_edm_sampleservice_v4.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/mdk_i18n_l10n/Actions/com_sap_edm_sampleservice_v4/Service/DownloadStartedMessage.action",
    "OnFailure": "/mdk_i18n_l10n/Actions/com_sap_edm_sampleservice_v4/Service/SyncFailureMessage.action"
}