{
	"CreateLinks": [],
	"OnFailure": "/MDKApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/MDKApp/Actions/CreateEntitySuccessMessage.action",
	"Properties": {
		"Category": "#Control:Category/#Value",
		"CategoryName": "#Control:CategoryName/#Value",
		"MainCategory": "#Control:MainCategory/#Value",
		"MainCategoryName": "#Control:MainCategoryName/#Value",
		"NumberOfProducts": "#Control:NumberOfProducts/#Value",
		"UpdatedTimestamp": "#Control:UpdatedTimestamp/#Value"
	},
	"Target": {
		"EntitySet": "ProductCategories",
		"Service": "/MDKApp/Services/SampleServiceV2.service"
	},
	"ActionResult": {
		"_Name": "create"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}