{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/mdk_errorarchive/Pages/SampleServiceV4_PurchaseOrderHeaders/PurchaseOrderHeaders_Edit.page",
    "_Type": "Action.Type.Navigation"
}