{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MDK_ErrorArchive/Pages/SampleServiceV4_PurchaseOrderHeaders/PurchaseOrderHeaders_Create.page",
    "_Type": "Action.Type.Navigation"
}