{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "SalesOrderItems",
		"Service": "/MDKApp/Services/Sample.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties":  {
	"CurrencyCode": "#Control:CurrencyCode/#Value",
	"DeliveryDate": "#Control:DeliveryDate/#Value",
	"GrossAmount": "#Control:GrossAmount/#Value",
	"ItemNumber": "#Control:ItemNumber/#Value",
	"NetAmount": "#Control:NetAmount/#Value",
	"ProductId": "#Control:ProductId/#Value",
	"Quantity": "#Control:Quantity/#Value",
	"QuantityUnit": "#Control:QuantityUnit/#Value",
	"SalesOrderId": "#Control:SalesOrderId/#Value",
	"TaxAmount": "#Control:TaxAmount/#Value"
},
	"UpdateLinks": [],
	"ActionResult": {
		"_Name": "update"
	},
	"OnSuccess": "/MDKApp/Actions/UpdateEntitySuccessMessage.action",
	"OnFailure": "/MDKApp/Actions/UpdateEntityFailureMessage.action"
}