{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/mdkapp/Actions/com_sap_edm_sampleservice_v4/Service/InitializeOfflineFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"Service": "/mdkapp/Services/com_sap_edm_sampleservice_v4.service",
	"DefiningRequests": [
		{
			"Name": "Customers",
			"Query": "Customers"
		},
		{
			"Name": "ProductCategories",
			"Query": "ProductCategories"
		},
		{
			"Name": "Products",
			"Query": "Products",
			"AutomaticallyRetrievesStreams": true
		},
		{
			"Name": "ProductTexts",
			"Query": "ProductTexts"
		},
		{
			"Name": "PurchaseOrderHeaders",
			"Query": "PurchaseOrderHeaders"
		},
		{
			"Name": "PurchaseOrderItems",
			"Query": "PurchaseOrderItems"
		},
		{
			"Name": "SalesOrderHeaders",
			"Query": "SalesOrderHeaders"
		},
		{
			"Name": "SalesOrderItems",
			"Query": "SalesOrderItems"
		},
		{
			"Name": "Stock",
			"Query": "Stock"
		},
		{
			"Name": "Suppliers",
			"Query": "Suppliers"
		}
	]
}