{
    "Service": "/BarcodeScanning/Services/com_sap_edm_sampleservice_v4.service",
    "DefiningRequests": [{
        "Name": "Products",
        "Query": "Products"
    },
    {
        "Name": "Stock",
        "Query": "Stock"
    },
     {
        "Name": "Suppliers",
        "Query": "Suppliers"
    }],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/BarcodeScanning/Actions/SampleServiceV4/Service/SyncFailureMessage.action",
    "OnSuccess": "/BarcodeScanning/Rules/ErrorArchive/ErrorArchive_CheckForSyncError.js"
}