{
    "Animated": true,
    "CompletionMessage": "Logs Uploaded",
    "CompletionTimeout": 2,
    "Message": "Uploading Log Files...",
    "OnSuccess": "/mdk_geolocation/Actions/Logging/UploadLog.action",
    "_Type": "Action.Type.ProgressBanner"
}