{
    "Service": "/MDK_ErrorArchive/Services/SampleServiceV4.service",
    "DefiningRequests": [{
            "Name": "PurchaseOrderHeaders",
            "Query": "PurchaseOrderHeaders"
        },
        {
            "Name": "PurchaseOrderItems",
            "Query": "PurchaseOrderItems"
        },
        {
            "Name": "Suppliers",
            "Query": "Suppliers"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/MDK_ErrorArchive/Actions/SampleServiceV4/Service/SyncFailureMessage.action",
    "OnSuccess": "/MDK_ErrorArchive/Rules/ErrorArchive/ErrorArchive_CheckForSyncError.js"
}