{
    "PopoverItems": [{
            "Enabled": true,
            "Icon": "sap-icon://headset",
            "OnPress": "/MDK_Geolocation/Actions/Application/NavToSupport.action",
            "Title": "Support",
            "Visible": true
        },
        {
            "Enabled": true,
            "Icon": "sap-icon://refresh",
            "OnPress": "/MDK_Geolocation/Actions/Application/AppUpdateProgressBanner.action",
            "Title": "Check for Updates",
            "Visible": "$(PLT,true,true,false)"
        },
        {
            "Enabled": true,
            "Icon": "sap-icon://hint",
            "OnPress": "/MDK_Geolocation/Actions/Application/NavToAbout.action",
            "Title": "About",
            "Visible": true
        },
        {
            "Enabled": true,
            "Icon": "sap-icon://reset",
            "OnPress": "/MDK_Geolocation/Actions/Application/ResetMessage.action",
            "Title": "Reset",
            "Visible": true
        },
        {
            "Enabled": true,
            "Icon": "sap-icon://log",
            "OnPress": "/MDK_Geolocation/Actions/Application/Logout.action",
            "Title": "Logout",
            "Visible": "/MDK_Geolocation/Rules/Application/ClientIsMultiUserMode.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}