{
	"CreateLinks": [],
	"OnFailure": "/MDKApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/MDKApp/Actions/CreateEntitySuccessMessage.action",
	"Properties": {
		"LotSize": "#Control:LotSize/#Value",
		"MinStock": "#Control:MinStock/#Value",
		"ProductId": "#Control:ProductId/#Value",
		"Quantity": "#Control:Quantity/#Value",
		"QuantityLessMin": "#Control:QuantityLessMin/#Value",
		"UpdatedTimestamp": "#Control:UpdatedTimestamp/#Value"
	},
	"Target": {
		"EntitySet": "Stock",
		"Service": "/MDKApp/Services/SampleServiceV2.service"
	},
	"ActionResult": {
		"_Name": "create"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}