{
	"Target": {
		"EntitySet": "Customers",
		"Service": "/MDK_Styling/Services/Sample.service",
		"ReadLink": "{@odata.readLink}"
	},
	"OnSuccess": "/MDK_Styling/Actions/DeleteEntitySuccessMessage.action",
	"OnFailure": "/MDK_Styling/Actions/DeleteEntityFailureMessage.action",
	"ActionResult": {
		"_Name": "delete"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity"
}