{
    "_Type": "Action.Type.Message",
    "Message": "Update now?",
    "Title": "Confirmation",
    "OKCaption": "OK",
    "CancelCaption": "CANCEL",
    "ActionResult": {
        "_Name": "OnWillUpdate"
    }
}