{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MDK_ErrorArchive/Pages/SampleServiceV4_Suppliers/Suppliers_CreatePurchaseOrderHeader.page",
    "_Type": "Action.Type.Navigation"
}