{
    "Service": "/multiuserapp/Services/com_sap_edm_sampleservice_v4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/multiuserapp/Actions/com_sap_edm_sampleservice_v4/Service/SyncFailureMessage.action",
    "OnSuccess": "/multiuserapp/Rules/com_sap_edm_sampleservice_v4/ErrorArchive_CheckForSyncError.js"
}