{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Target": {
		"EntitySet": "ProductCategories",
		"Service": "/MDK_Styling/Services/SampleServiceV2.service",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"Category": "#Control:Category/#Value",
		"CategoryName": "#Control:CategoryName/#Value",
		"MainCategory": "#Control:MainCategory/#Value",
		"MainCategoryName": "#Control:MainCategoryName/#Value",
		"NumberOfProducts": "#Control:NumberOfProducts/#Value",
		"UpdatedTimestamp": "#Control:UpdatedTimestamp/#Value"
	},
	"UpdateLinks": [],
	"ActionResult": {
		"_Name": "update"
	},
	"OnSuccess": "/MDK_Styling/Actions/UpdateEntitySuccessMessage.action",
	"OnFailure": "/MDK_Styling/Actions/UpdateEntityFailureMessage.action"
}