{
    "ActionResult": {
        "_Name": "UploadLog"
    },
    "ActivityIndicatorText": "Uploading...",
    "OnFailure": "/demosampleapp/Actions/Logging/LogUploadFailure.action",
    "OnSuccess": "/demosampleapp/Actions/Logging/LogUploadSuccessful.action",
    "ShowActivityIndicator": false,
    "_Type": "Action.Type.Logger.Upload"
}