{
	"_Type": "Action.Type.ODataService.Create",
	"Service": "/MDKOnlineApp/Services/Sample.service",
	"OnSuccess": "/MDKOnlineApp/Actions/Service/OpenService.action",
	"OnFailure": "/MDKOnlineApp/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Initializing Application...",
	"ActionResult": {
		"_Name": "init"
	}
}