{
    "Service": "/MDKOnlineApp/Services/SampleServiceV4.service",
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "OnSuccess": "/MDKOnlineApp/Actions/Service/InitializeOnlineSuccessMessage.action",
    "OnFailure": "/MDKOnlineApp/Actions/Service/InitializeOnlineFailureMessage.action",
    "ActionResult": {
        "_Name": "init"
    }
}