{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/MDK_Styling/Pages/SalesOrderHeaders/SalesOrderHeaders_CreateSalesOrderItem.page",
    "_Type": "Action.Type.Navigation"
}