{
    "ParentLink": {
        "Property": "PurchaseOrderItems",
        "Target": {
            "EntitySet": "Products",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/MDK_ErrorArchive/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/MDK_ErrorArchive/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "CurrencyCode": "#Control:CurrencyCode/#Value",
        "GrossAmount": "#Control:GrossAmount/#Value",
        "ItemNumber": "#Control:ItemNumber/#Value",
        "NetAmount": "#Control:NetAmount/#Value",
        "ProductID": "#Control:ProductID/#SelectedValue",
        "PurchaseOrderID": "#Control:PurchaseOrderID/#SelectedValue",
        "Quantity": "#Control:Quantity/#Value",
        "QuantityUnit": "#Control:QuantityUnit/#Value",
        "TaxAmount": "#Control:TaxAmount/#Value"
    },
    "Target": {
        "EntitySet": "PurchaseOrderItems",
        "Service": "/MDK_ErrorArchive/Services/SampleServiceV4.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}