{
    "_Type": "Action.Type.BannerMessage",
    "Message": "Upload failed!",
    "Duration": 0,
    "Animated": false,
    "OnActionLabelPress": "/MDK_Styling/Actions/ErrorArchive/NavToErrorArchive_List.action",
    "ActionLabel": "View Errors"
}