{
    "Service": "/DemoSampleApp/Services/SampleServiceV2.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "SalesOrderHeaders",
            "Query": "SalesOrderHeaders"
        },
        {
            "Name": "SalesOrderItems",
            "Query": "SalesOrderItems"
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/DemoSampleApp/Actions/Service/SyncFailureMessage.action",
    "OnSuccess": "/DemoSampleApp/Rules/ErrorArchive/ErrorArchive_CheckForSyncError.js"
}