{
    "CreateLinks": [],
    "OnFailure": "/MDKApp/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/MDKApp/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "CurrencyCode": "#Control:CurrencyCode/#Value",
        "GrossAmount": "#Control:GrossAmount/#Value",
        "NetAmount": "#Control:NetAmount/#Value",
        "PurchaseOrderId": "#Control:PurchaseOrderId/#Value",
        "SupplierId": "#Control:SupplierId/#SelectedValue",
        "TaxAmount": "#Control:TaxAmount/#Value"
    },
    "Target": {
        "EntitySet": "PurchaseOrderHeaders",
        "Service": "/MDKApp/Services/SampleServiceV2.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}