{
    "Service": "/DemoSampleApp/Services/SampleServiceV4.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products"
        },
        {
            "Name": "SalesOrderHeaders",
            "Query": "SalesOrderHeaders"
        },
        {
            "Name": "SalesOrderItems",
            "Query": "SalesOrderItems"
        }
    ],
    "_Type": "Action.Type.ODataService.Initialize",
    "ShowActivityIndicator": true,
    "ActivityIndicatorText": "Downloading...",
    "ActionResult": {
        "_Name": "init"
    },
    "OnFailure": "/DemoSampleApp/Actions/SampleServiceV4/Service/InitializeOfflineFailureMessage.action"
}