{
    "_Type": "Action.Type.OfflineOData.Close",
    "Service": "/MDK_i18n_l10n/Services/SampleServiceV4.service",
    "Force": true,
    "ActionResult": {
        "_Name": "close"
    },
    "OnSuccess": "/MDK_i18n_l10n/Actions/Service/CloseOfflineSuccessMessage.action",
    "OnFailure": "/MDK_i18n_l10n/Actions/Service/CloseOfflineFailureMessage.action"
}