{
	"_Type": "Action.Type.RestService.SendRequest",
	"ActionResult": {
		"_Name": "CreatePet"
	},
	"OnSuccess": "/MDK_Petstore/Actions/ClosePage_Complete.action",
	"Target": {
		"Service": "/MDK_Petstore/Services/petstore.service",
		"Path": "/pet",
		"RequestProperties": {
			"Method": "POST",
			"Body": {
				"name": "#Control:FCCreatePet/#Value",
				"status": "#Control:FCCreateStatus/#Value"
			}
		}
	}
}