{
	"Service": "/MDK_Annotations/Services/SampleServiceV2.service",
	"_Type": "Action.Type.ODataService.Open",
	"OnSuccess": "/MDK_Annotations/Actions/Service/CreateOpenServiceSuccessMessage.action",
	"OnFailure": "/MDK_Annotations/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ActionResult": {
		"_Name": "init"
	}
}