{
    "Message": "Upload in progress...",
    "CompletionMessage": "Sync completed",
    "CompletionTimeout": 7,
    "OnSuccess": "/deeplinkintomdkapp/Actions/com_sap_edm_sampleservice_v4/Service/UploadOffline.action",
    "OnFailure": "/deeplinkintomdkapp/Actions/com_sap_edm_sampleservice_v4/Service/SyncFailureMessage.action",
    "_Type": "Action.Type.ProgressBanner"
}