{
	"OnFailure": "/DemoSampleApp/Actions/UpdateCustomerEntityFailureMessage.action",
	"OnSuccess": "/DemoSampleApp/Actions/CloseModalPage_Complete.action",
	"Properties": {
		"EmailAddress": "#Control:FCEmail/#Value",
		"FirstName": "#Control:FCFirstName/#Value",
		"LastName": "#Control:FCLastName/#Value",
		"PhoneNumber": "#Control:FCPhone/#Value"
	},
	"Target": {
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}",
		"Service": "/DemoSampleApp/Services/Sample.service"
	},
	"ValidationRule": "/DemoSampleApp/Rules/EmailValidation.js",
	"_Type": "Action.Type.ODataService.UpdateEntity"
}