{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Customers_CreateEntity"
	},
	"OnFailure": "/demosampleapp/Actions/CreateCustomerEntityFailureMessage.action",
	"OnSuccess": "/demosampleapp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/demosampleapp/Services/SampleServiceV4.service",
		"EntitySet": "Customers"
	},
	"Properties": {
		"DateOfBirth": "#Control:FCCreateDOB/#Value",
		"FirstName": "#Control:FCCreateFirstName/#Value",
		"LastName": "#Control:FCCreateLastName/#Value",
		"PhoneNumber": "#Control:FCCreatePhone/#Value"
	}
}