{
	"Target": {
		"Path": "/pet",
		"RequestProperties": {
			"Body": {
				"categoryname": "#Control:FCCreateCategory/#Value",
				"name": "#Control:FCCreatePet/#Value",
				"status": "#Control:FCCreateStatus/#Value"
			},
			"Method": "POST"
		},
		"Service": "/MDK_Petstore/Services/petstore.service"
	},
	"_Type": "Action.Type.RestService.SendRequest"
}