{
	"Service": "/MDKOnlineApp/Services/SampleServiceV2.service",
	"_Type": "Action.Type.ODataService.Open",
	"OnSuccess": "/MDKOnlineApp/Actions/Service/CreateOpenServiceSuccessMessage.action",
	"OnFailure": "/MDKOnlineApp/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ActionResult": {
		"_Name": "init"
	}
}